apiVersion: v1
kind: Service
metadata:
  name: hello-minikube
  labels:
    app: hello-minikube
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: hello-minikube
    tier: hello-minikube
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-minikube
  labels:
    app: hello-minikube
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hello-minikube
        tier: hello-minikube
    spec:
      containers:
      - image: 127.0.0.1:30400/hello-minikube:latest
        name: hello-minikube
        ports:
        - containerPort: 80
          name: hello-minikube
